; CODE TO ALTERNATE TOGGLE ALL THE 8 BITS IN PORT 1 OF 8051
START:
		MOV P1, #0FFH
		CALL DELAY
		MOV P1, #00H
		CALL DELAY
		SJMP START

DELAY:
		MOV R2, #0AH
LOOP1:  MOV R1, #0C8H
LOOP0:  MOV R0, #0FFH
WAIT:   DJNZ R0, WAIT
		DJNZ R1, LOOP0
		DJNZ R2, LOOP1
		RETI
		END
