;SERIAL COMMUNICATION FROM z TO ! ALL ASCII CHARACTERS WITH A DELAY OF 0.5 SECONDS
START:
		MOV 	TMOD, 	#21H	; TIMER 1, MODE 2
		MOV 	TH1, 	#0FAH 	; BAUD RATE SET TO 4800 HERTZ
		MOV 	SCON, 	#50H	; SERIAL MODE 1
		SETB 	TR1	  			; START THE TIMER 1
		MOV 	R2, 	#'z'	; TRANSFER 
		
LOOP:	
		ACALL 	T		  		;CALL T FUNCTION
		DJNZ 	R2, 	LOOP
DOWN:	SJMP 	DOWN
		
T:		MOV 	SBUF, 	R2   	;SERIAL COMM FUNCTION
HERE:	JNB 	TI, 	HERE  	; TILL THE ENTIRE BYTE IS TRANSFERRED
		ACALL 	DELAY
		CLR 	TI		  		; TO SEND THE NEXT BYTE
		RET	
		
DELAY:

		MOV 	R0, 	#14H	;50 MILISECONDS * 20 TIMES

UP:    	;MOV 	TMOD, 	#01H	;TIMER MODE SELECTION
		MOV 	TL0, 	#0B0H 	;LOAD TL COUNTER VALUE
		MOV 	TH0, 	#3CH  	;LOAD TH COUNTER VALUE
		SETB 	TR0		 		;START TIMER

	   

THIS:  	JNB 	TF0, 	THIS  	;WAIT TILL TF = 1 (OVERFLOW)
		CLR 	TR0				;STOP TIMER
		CLR 	TF0				;CLEAR TF0
		DJNZ 	R0, 	UP		;
		RETI
		END
