;SERIAL COMMUNICATION
START:
		MOV TMOD, #20H; TIMER 1, MODE 2
		MOV TH1, #0FAH ; BAUD RATE SET TO 4800 HERTZ
		MOV SCON, #50H; SERIAL MODE 1
		SETB TR1	  ; START THE TIMER 1
UP:		MOV SBUF, #'G'; TRANSFER G
HERE:	JNB TI, HERE  ; TILL THE ENTIRE BYTE IS TRANSFERRED
		CLR TI		  ; TO SEND THE NEXT BYTE
		SJMP UP
		END
